#server settings
server:
    port : 8080
    address : localhost
    sessionTimeout : 30
    #contextPath : /
    #Tomcat specifics
    tomcat:
        accessLogEnabled : false
        protocolHeader : x-forwarded-proto
        remoteIpHeader : x-forwarded-for
        basedir:
        backgroundProcessorDelay : 30 # secs
logging:
    config : classpath:logback.xml
    level :
      org.springframework : DEBUG
      org.springframework.data : ERROR
      org.hibernate : ERROR
      javax.persistence : ERROR
      com.woawi : DEBUG


spring :
    jpa :
        database : MYSQL
        show-sql : false
        generate-ddl : true

        hibernate :
            ddl-auto : update
            naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy

        properties :
            hibernate :
                dialect : org.hibernate.dialect.MySQL5Dialect

    freemarker :
        suffix : .ftl
        request-context-attribute : request
        expose-request-attributes : true
    jackson:
        date-format : yyyyMMddHHmmss

